# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d278e6ce4934aa6311b9e2d6716e31dbc7218e0e1054af215fbb4ce76d1e49311a933ec7e03cfb401b8d38d162fa08871f0354204aa164e63203fc79924734

test:
  secret_key_base: 347c04fe33a117eef003e354cfb5199f692595c8815d06ebef6d395735792db9a7369c2e1628998ba9e4ae7f599f3e2dd6448c0de375a4d50ec12842358d2c80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
